name: railzway

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  migrate:
    image: ghcr.io/railzwaylabs/railzway-migrate:latest
    depends_on:
      postgres:
        condition: service_healthy
    command: ["up", "--database-url", "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"]
    restart: "no"

  admin:
    image: ghcr.io/railzwaylabs/railzway-admin-all-in-one:latest
    env_file:
      - ../../config/docker/admin.env
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started
    ports:
      - "8080:8080"

  scheduler:
    image: ghcr.io/railzwaylabs/railzway-scheduler:latest
    env_file:
      - ../../config/docker/scheduler.env
    depends_on:
      migrate:
        condition: service_completed_successfully

  api:
    profiles: ["api"]
    image: ghcr.io/railzwaylabs/railzway-api:latest
    env_file:
      - ../../config/docker/admin.env
    depends_on:
      migrate:
        condition: service_completed_successfully

volumes:
  pgdata:
